id: P003013
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7949
  title: ངག་དབང་བཟང་པོའི་ཞལ་གདམས་མགུར་འབུམ་གྱི་རིམ་པ་གྲུབ་པ་བཅུད་ཀྱི་དགའ་སྟོན།
  author: ''
  volumes:
    71aa7ff093984c3b8e944900deda02a5:
      image_group_id: I1KG8761
      title: ''
      volume_number: 1
      total_pages: 54
