id: P003013
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:34:20.694114
source_metadata:
  id: bdr:W2CZ7949
  title: ངག་དབང་བཟང་པོའི་ཞལ་གདམས་མགུར་འབུམ་གྱི་རིམ་པ་གྲུབ་པ་བཅུད་ཀྱི་དགའ་སྟོན།
  author: ''
  volumes:
    71aa7ff093984c3b8e944900deda02a5:
      image_group_id: I1KG8761
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
