id: IDDED7898
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T05:53:08+00:00'
last_modified: '2022-06-07T17:00:27.731101+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7949
  title: ངག་དབང་བཟང་པོའི་ཞལ་གདམས་མགུར་འབུམ་གྱི་རིམ་པ་གྲུབ་པ་བཅུད་ཀྱི་དགའ་སྟོན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6B6E:
      image_group_id: I1KG8761
      title: ''
      total_pages: 54
      order: 1
      base_file: 6B6E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
